//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Director.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Director.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 //-----------------------------------------------------------------------------
        ///
        ///PANIC &lt;- 0
        ///TANK &lt;- 1
        ///DELAY &lt;- 2
        ///ONSLAUGHT &lt;- 3
        ///
        /////-----------------------------------------------------------------------------
        ///
        ///SharedOptions &lt;-
        ///{
        ///	A_CustomFinale_StageCount = 9
        ///	
        /// 	A_CustomFinale1 = PANIC
        ///	A_CustomFinaleValue1 = 1
        ///	
        /// 	A_CustomFinale2 = PANIC
        ///	A_CustomFinaleValue2 = 1
        ///
        ///	A_CustomFinale3 = DELAY
        ///	A_CustomFinaleValue3 = 15
        ///
        ///	A_CustomFinale4 = TANK
        ///	A_CustomFinaleValue4 = 1
        ///	A_CustomFinaleM [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string c2m5_concert_finale {
            get {
                return ResourceManager.GetString("c2m5_concert_finale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //-----------------------------------------------------
        ///local PANIC = 0
        ///local TANK = 1
        ///local DELAY = 2
        /////-----------------------------------------------------
        ///
        ///DirectorOptions &lt;-
        ///{
        ///	//-----------------------------------------------------
        ///
        ///	 A_CustomFinale_StageCount = 8
        ///	 
        ///	 A_CustomFinale1 = PANIC
        ///	 A_CustomFinaleValue1 = 2
        ///	 
        ///	 A_CustomFinale2 = DELAY
        ///	 A_CustomFinaleValue2 = 12
        ///	 
        ///	 A_CustomFinale3 = TANK
        ///	 A_CustomFinaleValue3 = 1
        ///	 
        ///	 A_CustomFinale4 = DELAY
        ///	 A_CustomFinaleValue4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string c3m4_plantation_finale {
            get {
                return ResourceManager.GetString("c3m4_plantation_finale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cefaedfe100000000e000000d83e0c000100000164656661756c74000000240000000100000000000000008054c40000c8c100fc8fc30000c8c30080d44300fc8fc300fc8fc300fc8fc30000000001000000550000000000000001000000540000000400000000006051c4000048c100fc8fc301010000000040cec3000048c100fc8fc301020000000040cec30040ce4300fc8fc30103000000006051c40040ce4300fc8fc30100000000000000000000000000000000f0420000f042553b283fe83c253f77722c3f05cc293f400000000000050000000000000002150000000109000000011d000000011f00000002540000006a000000000000200040cec4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FinaleStandardScriptNav {
            get {
                return ResourceManager.GetString("FinaleStandardScriptNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 versioninfo
        ///{
        ///	&quot;editorversion&quot; &quot;400&quot;
        ///	&quot;editorbuild&quot; &quot;8864&quot;
        ///	&quot;mapversion&quot; &quot;95&quot;
        ///	&quot;formatversion&quot; &quot;100&quot;
        ///	&quot;prefab&quot; &quot;0&quot;
        ///}
        ///visgroups
        ///{
        ///}
        ///viewsettings
        ///{
        ///	&quot;bSnapToGrid&quot; &quot;1&quot;
        ///	&quot;bShowGrid&quot; &quot;1&quot;
        ///	&quot;bShowLogicalGrid&quot; &quot;0&quot;
        ///	&quot;nGridSpacing&quot; &quot;1&quot;
        ///}
        ///palette_plus
        ///{
        ///	&quot;color0&quot; &quot;255 255 255&quot;
        ///	&quot;color1&quot; &quot;255 255 255&quot;
        ///	&quot;color2&quot; &quot;255 255 255&quot;
        ///	&quot;color3&quot; &quot;255 255 255&quot;
        ///	&quot;color4&quot; &quot;255 255 255&quot;
        ///	&quot;color5&quot; &quot;255 255 255&quot;
        ///	&quot;color6&quot; &quot;255 255 255&quot;
        ///	&quot;color7&quot; &quot;255 255 255&quot;
        ///	&quot;color8&quot; &quot;255 255 255&quot;
        ///	&quot;color9&quot; &quot;255 255 255&quot;        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FinaleStandardScriptVmf {
            get {
                return ResourceManager.GetString("FinaleStandardScriptVmf", resourceCulture);
            }
        }
    }
}
